export enum FormFieldNames {
  FULL_NAME = "fullName",
  SHORT_NAME = "shortName",
  ADDRESS = "address",
  PASSPORT_SERIAL = "passportSerial",
  PASSPORT_NUMBER = "passportNumber",
  ATTORNEY = "attorney",
  OWNER = "owner",
  PERIOD = "period",
  FORM = "form",
  DETAILS = "details",
  SERIAL = "serial",
  NUMBER = "number",
  ISSUES_BY = "issuedBy",
  ISSUES_DATE = "issuedDate",
  NAME = "name",
  MODEL = "model",
  CAR_YEAR = "carYear",
  STATE_NUMBER = "stateNumber",
  BODY_NUMBER = "bodyNumber",
  COST_NUMBER = "costNumber",
  COST_TEXT = "costText",
  CITY = "city",
  YEAR = "year",
}
