export * from "./buyer";
export * from "./car";
export * from "./certificate";
export * from "./contractFields";
export * from "./formFileds";
export * from "./otherDetails";
export * from "./payment";
export * from "./person";
export * from "./salesman";
